export const TYPE_ACTIVITY_LIST = 'TYPE_ACTIVITY_LIST'
export const SET_NEXT_PAGE_ACTIVITY_LIST = 'SET_NEXT_PAGE_ACTIVITY_LIST'
export const TYPE_ACTIVITY_DETAIL = 'TYPE_ACTIVITY_DETAIL'
export const TYPE_ACTIVITY_CREATE = 'TYPE_ACTIVITY_CREATE'
export const ACTIVITY_DEFAULT = {
  total: 0,
  list: [],
}
