export const TYPE_COURSE_LIST = 'TYPE_COURSE_LIST'
export const SET_NEXT_PAGE_COURSE_LIST = 'SET_NEXT_PAGE_COURSE_LIST'
export const TYPE_COURSE_TEACHER = 'TYPE_COURSE_TEACHER'
export const TYPE_COURSE_CHAPTER = 'TYPE_COURSE_CHAPTER'
export const TYPE_COURSE_EXERCISE = 'TYPE_COURSE_EXERCISE'
export const TYPE_COURSE_EXERCISEQUSSTION = 'TYPE_COURSE_EXERCISEQUSSTION'
export const TYPE_COURSE_EXERCISEPOINT = 'TYPE_COURSE_EXERCISEPOINT'

export const COURSE_DEFAULT = {
  total: 0,
  list: [],
}
