export const TYPE_PROJECT_LIST = 'TYPE_PROJECT_LIST'
export const TYPE_MEMBER_LIST = 'TYPE_MEMBER_LIST'
export const SET_NEXT_PAGE_MEMBER_LIST = 'SET_NEXT_PAGE_MEMBER_LIST'
export const TYPE_MEMBER_INFORMATION = 'TYPE_MEMBER_INFORMATION'
export const MEMBER_DEFAULT = {
  total: 0,
  list: [],
}
