export const TYPE_PROJECT_LIST = 'TYPE_PROJECT_LIST'
export const SET_NEXT_PAGE_PROJECT_LIST =  'SET_NEXT_PAGE_PROJECT_LIST'
export const TYPE_PROJECT_DETAIL = 'TYPE_PROJECT_DETAIL'
export const TYPE_PROJECT_APPLYCATION = 'TYPE_PROJECT_APPLYCATION'
export const TYPE_POINT_DETAIL = 'TYPE_POINT_DETAIL'
export const TYPE_POINT_COUNT = 'TYPE_POINT_COUNT'
export const PROJECT_DEFAULT = {
  total: 0,
  list: [],
}
